"""initial schema

Revision ID: ab0e47f61e38
Revises: 
Create Date: 2026-03-08 21:23:27.430846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab0e47f61e38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_sessions',
    sa.Column('room_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_phase_number', sa.Integer(), nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('experience_level', sa.String(length=10), nullable=False),
    sa.Column('role_type', sa.String(length=20), nullable=False),
    sa.Column('primary_language', sa.String(length=20), nullable=False),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interview_type', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_name')
    )
    op.create_index(op.f('ix_interview_sessions_status'), 'interview_sessions', ['status'], unique=False)
    op.create_table('coaching_notes',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('timestamp_seconds', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaching_notes_session_id'), 'coaching_notes', ['session_id'], unique=False)
    op.create_table('feedback_snapshots',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('pace', sa.String(length=10), nullable=False),
    sa.Column('filler_words', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_snapshots_session_id'), 'feedback_snapshots', ['session_id'], unique=False)
    op.create_table('interview_phases',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=False),
    sa.Column('phase_type', sa.String(length=20), nullable=False),
    sa.Column('interviewer_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'phase_number')
    )
    op.create_index(op.f('ix_interview_phases_session_id'), 'interview_phases', ['session_id'], unique=False)
    op.create_table('scorecards',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('interview_type', sa.String(length=20), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('overall_summary', sa.Text(), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('improvements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('category_scores',
    sa.Column('scorecard_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scorecard_id'], ['scorecards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_scores_scorecard_id'), 'category_scores', ['scorecard_id'], unique=False)
    op.create_table('key_moments',
    sa.Column('scorecard_id', sa.UUID(), nullable=False),
    sa.Column('timestamp_seconds', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scorecard_id'], ['scorecards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_moments_scorecard_id'), 'key_moments', ['scorecard_id'], unique=False)
    op.create_table('level_calibrations',
    sa.Column('scorecard_id', sa.UUID(), nullable=False),
    sa.Column('selected_level', sa.String(length=10), nullable=False),
    sa.Column('calibrated_level', sa.String(length=10), nullable=False),
    sa.Column('theta_path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strongest_area', sa.String(length=255), nullable=False),
    sa.Column('growth_area', sa.String(length=255), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scorecard_id'], ['scorecards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scorecard_id')
    )
    op.create_table('phase_scores',
    sa.Column('scorecard_id', sa.UUID(), nullable=False),
    sa.Column('phase_type', sa.String(length=20), nullable=False),
    sa.Column('interviewer_name', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scorecard_id'], ['scorecards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phase_scores_scorecard_id'), 'phase_scores', ['scorecard_id'], unique=False)
    op.create_table('session_analytics',
    sa.Column('scorecard_id', sa.UUID(), nullable=False),
    sa.Column('speaking_time_pct', sa.Float(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=False),
    sa.Column('filler_word_count', sa.Integer(), nullable=False),
    sa.Column('filler_word_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('questions_answered', sa.Integer(), nullable=False),
    sa.Column('phases_completed', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scorecard_id'], ['scorecards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scorecard_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_analytics')
    op.drop_index(op.f('ix_phase_scores_scorecard_id'), table_name='phase_scores')
    op.drop_table('phase_scores')
    op.drop_table('level_calibrations')
    op.drop_index(op.f('ix_key_moments_scorecard_id'), table_name='key_moments')
    op.drop_table('key_moments')
    op.drop_index(op.f('ix_category_scores_scorecard_id'), table_name='category_scores')
    op.drop_table('category_scores')
    op.drop_table('scorecards')
    op.drop_index(op.f('ix_interview_phases_session_id'), table_name='interview_phases')
    op.drop_table('interview_phases')
    op.drop_index(op.f('ix_feedback_snapshots_session_id'), table_name='feedback_snapshots')
    op.drop_table('feedback_snapshots')
    op.drop_index(op.f('ix_coaching_notes_session_id'), table_name='coaching_notes')
    op.drop_table('coaching_notes')
    op.drop_index(op.f('ix_interview_sessions_status'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    # ### end Alembic commands ###
