"""add user_id to sessions

Revision ID: ccd09d8aa486
Revises: ab0e47f61e38
Create Date: 2026-03-08 21:23:40.926007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd09d8aa486'
down_revision: Union[str, None] = 'ab0e47f61e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_interview_sessions_user_id'), 'interview_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_sessions_user_id'), table_name='interview_sessions')
    op.drop_column('interview_sessions', 'user_id')
    # ### end Alembic commands ###
